### ISSUE TITLE
Rasmify changes words

### ISSUE THREAD

**Issue by r-shahpasand** [telota/rasmify#1]
Sometimes it changes letters incorrectly so we have a new word different from the one we entered. For example
وَهَيِّئۡ  
changes to 
وهىٮ
which is totally a different word.

**Comment by suchmaske** [comment]
Hey, sorry for the late response @RShpd 

Could you try entering the word here and tell me whether it is rendered correctly there?

https://telota.github.io/rasmify.js/demo/

**Comment by r-shahpasand** [comment]
Hi, I tried again and the problem still exists. I'm using exactly the same version of rasmify which you have sent the link. @suchmaske

**Comment by suchmaske** [comment]
@RShpd Would you be so kind and post the word how it should look properly? (I developed this with a former colleague who speaks arabic, however I do not.)

**Comment by r-shahpasand** [comment]
Yes of course. The rendered form of 
وَهَيِّئۡ 
should be 
وهىى
The word in the example above should end with `ى` when it's rendered but in the current version of rasmify it ends with `ٮ` character. @suchmaske

**Comment by suchmaske** [comment]
@RShpd Thanks again for pointing out the issue.

Thanks to your report I detected that we also did this wrong in our test data. I have consulted with my ex-colleague and fixed the issue locally for the Javascript version of rasmify. I will keep you posted when the PHP version is updated.

**Comment by r-shahpasand** [comment]
Thank you. I'm looking forward to the update. @suchmaske

**Comment by suchmaske** [comment]
Hey @RShpd 

I have done a re-implementation of rasmify for PHP. I have fixed the error there.

https://github.com/suchmaske/rasmiphize
https://packagist.org/packages/suchmaske/rasmiphize

**Comment by suchmaske** [comment]
If you are looking for the updated demo page, check it out here: https://suchmaske.github.io/rasmifize/demo/

**Comment by r-shahpasand** [comment]
Fantastic. It works as it should.
